### ISSUE TITLE
Icons in Components

### ISSUE THREAD

**Issue by Wamy-Dev** [sira-design/sira#75]
[The inputs](https://www.sira-design.party/docs/components/input) are very nice, but would it be possible to add left and right icons using a component like [Mantine and others](https://mantine.dev/core/input/#icon-and-right-section)? This would add a lot to the inputs and make them look a lot better.

**Comment by Wamy-Dev** [comment]
I would like to change this request to add Icon Components to a lot of items now that I am looking around more. Some items I would like to see icon components in is

- [ ] [Dropdown](https://www.sira-design.party/docs/components/dropdown)
- [ ] [Button](https://www.sira-design.party/docs/components/button)
- [ ] [Inputs](https://www.sira-design.party/docs/components/input)
- [ ] [Badges](https://www.sira-design.party/docs/components/badge)
- [ ] [Table Headers](https://www.sira-design.party/docs/components/table)

**Comment by riccox** [comment]
Hi @Wamy-Dev ,
I'm glad to see u love this.
I have added your requests to TODO for Sira.
You will see them soon!

**Comment by riccox** [comment]
@Wamy-Dev 
Completed in release version [v0.11.0](https://github.com/sira-design/sira/releases/tag/v0.11.0).
Now, you can use div element to combine these component with its slot.
See more details in docs below.
- [dropdown](https://www.sira-design.party/docs/components/dropdown#slot)
- [input](https://www.sira-design.party/docs/components/input#slot)
- [button](https://www.sira-design.party/docs/components/button#slot)
- [badge](https://www.sira-design.party/docs/components/badge#slot)
- [table](https://www.sira-design.party/docs/components/table#default)
