### ISSUE TITLE
Image Component

### ISSUE THREAD

**Issue by Wamy-Dev** [sira-design/sira#76]
Would be really interested in an a custom Image component. Sorta like [Mantine does](https://mantine.dev/core/image/)

**Comment by riccox** [comment]
Hi @Wamy-Dev ,
Sira is a design-system based on Tailwindcss which only focus on css styles now, I do not plan to realize same functions like Mantine (ex: controll image loading states...) after my reflection.
At same time, tailwindcss had some classes to control styles on `img` (like aspect-ratio, object Fit...) already.
So, image component will be considered as a preflight styles to add basic border-radius on `img` element in next release version.
