### ISSUE TITLE
How to change background Color?

### ISSUE THREAD

**Issue by Wamy-Dev** [sira-design/sira#77]
I can't really seem to figure it out using Sira. It is set to #000 which I am not a huge fan of regarding the dark mode.

**Comment by riccox** [comment]
Does u wanna to disable auto dark mode?

**Comment by Wamy-Dev** [comment]
> Does u wanna to disable auto dark mode?

No, just change the color of dark mode.

**Comment by riccox** [comment]
The default app background color is controled be "bw" token in [base styles](https://www.sira-design.party/docs/base/styles), which means "black to white".

You could read this [section](https://www.sira-design.party/docs/guide/customization#colors) to modify its color values.

If you want to override 'bw' colors in default "light" or "dark" mode,
just modify this config.
```js 
// tailwind.config.js
module.exports = {
  plugins: [
    require('@sira-ui/tailwind')({
      themes: [
        {
          // name & colorScheme should be "light" or "dark" to override
          name: 'light',
          colorScheme: 'light',
          colors: {
            bw: [
              // fill these color value (12 hex shades from 50 to 1100)
            ],
          },
        },
      ],
    }),
  ],
};
```

**Comment by riccox** [comment]
BTW, Sira's color system use a magic logic to generate & control color theme token in components.

Firstly, Sira uses [RadixUI Colors](https://www.radix-ui.com/colors) as the base for the color theme, you can see how to use the colors below.

We follow color reference below:

| Scale | Description                             |
| ----- | --------------------------------------- |
| 50    | App background                          |
| 100   | Subtle background                       |
| 200   | UI element background                   |
| 300   | Hovered UI element background           |
| 400   | Active / Selected UI element background |
| 500   | Subtle borders and separators           |
| 600   | UI element border and focus rings       |
| 700   | Hovered UI element border               |
| 800   | Solid backgrounds                       |
| 900   | Hovered solid backgrounds               |
| 1000  | Low-contrast text                       |
| 1100  | High-contrast text                      |

The 50~1100 scale works fine in both "light" or "dark" mode.
For example: the app background color is controled by `var(--sira-colors-bw-50)` css varible which will be "#000" in dark mode, but the `var(--sira-colors-bw-50)` css variable will be "#FFF" in light mode.

If you want to custom your own color token, u can also add a color name with a hex string or a color hex string array in `colors` option.

```js
// tailwind.config.js
module.exports = {
  plugins: [
    require('@sira-ui/tailwind')({
      themes: [
        {
          name: 'light',
          colorScheme: 'light',
          colors: {
            'yourowncolorname': [
              // fill these color value (12 hex shades from 50 to 1100)
              // or just give a single color hex string. (Sira will generate 12 shades for u by this single value)
            ],
          },
        },
      ],
    }),
  ],
};
```
