### ISSUE TITLE
Wrong corner radius on table head

### ISSUE THREAD

**Issue by gandous** [sira-design/sira#88]
The 2 top corner radius are too small on table head, making it clip trough the table
![Screenshot from 2023-11-01 20-14-41](https://github.com/sira-design/sira/assets/39808631/c3d26a74-4b17-4463-9279-634017570ac2)

**Comment by riccox** [comment]
@gandous Thanks!
Fixed in new release version [v0.11.7](https://github.com/sira-design/sira/releases/tag/v0.11.7).

And it will take some time to run ci for publish.
